
import { NextIntlClientProvider } from "next-intl";
import "../../../public/css/globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Cookie from "../components/Cookie";
import TopButton from "../components/TopButton";
export const metadata = {
  title: "EAS",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: '/img/logo.png', 
        href: '/img/logo.png', 
      }
    ],
  },
};

export default async function RootLayout({ children, params: { locale } }) {
  let messages;
  try {
    messages = (await import(`../../../messages/${locale}.json`)).default;
  } catch (error) {
    // notFound();
  }
  return (
    <html lang={locale}>
      <body>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <Header/>
            {children}
               <Cookie/>
        <TopButton/>
            <Footer/>
          </NextIntlClientProvider>
      </body>
    </html>
  );
}
